=== sousseinglu/PDS-STATE-MACHINE/src/XSD/SCXML_presentation.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3.org/2005/07/scxml"
 xmlns="http://www.w3.org/2005/07/scxml">
 
 <xsd:element name="scxml">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="datamodel" minOccurs="0" maxOccurs="1" />
    <xsd:element ref="state" minOccurs="1" maxOccurs="unbounded" />
   </xsd:sequence>
   <xsd:attribute name="version" type="xsd:string" fixed="1.0" />
   <xsd:attribute name="initialstate" type="xsd:IDREF" use="required" />
  </xsd:complexType>
 </xsd:element>
 
 <xsd:element name="datamodel">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="data" minOccurs="0" maxOccurs="unbounded" />
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>
 
 <xsd:element name="data">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
   </xsd:sequence>
   <xsd:attribute name="src" type="xsd:anyURI" />
   <xsd:attribute name="expr" type="xsd:string" />
   <xsd:attribute name="id" type="xsd:ID" use="required" />
  </xsd:complexType>
 </xsd:element>
 
 <xsd:element name="state">
  <xsd:complexType>
   <xsd:choice minOccurs="0" maxOccurs="unbounded">
    <xsd:element ref="onentry" minOccurs="0" maxOccurs="1" />
    <xsd:element ref="invoke" minOccurs="0" maxOccurs="1" />
    <xsd:element ref="transition" minOccurs="0" />
    <xsd:element ref="initial" minOccurs="0" maxOccurs="1" />
    <xsd:element ref="state" minOccurs="0" />
    <xsd:element ref="history" minOccurs="0" />
    <xsd:element ref="parallel" minOccurs="0" maxOccurs="1" />
    <xsd:element ref="onexit" minOccurs="0" maxOccurs="1" />
    <xsd:element ref="datamodel" minOccurs="0" maxOccurs="1" />
   </xsd:choice>
   
   <xsd:attribute name="id" type="xsd:ID" use="optional" />
   <xsd:attribute name="initial" type="xsd:IDREFS" />  
  </xsd:complexType>
 </xsd:element>
 
 <xsd:element name="initial">
  <xsd:complexType>
   <xsd:sequence>
				<xsd:element ref="transition" minOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:ID" use="optional" />
			<xsd:attribute name="src" type="xsd:anyURI" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="onentry">
		<xsd:complexType>
			<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="onexit">
		<xsd:complexType>
			<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="transition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="event" type="xsd:string" />
			<xsd:attribute name="cond" type="xsd:string" />
			<xsd:attribute name="target" type="xsd:IDREF" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="target">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="state" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="invoke">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="finalize" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="srcexpr" type="xsd:string" />
			<xsd:attribute name="targettype" type="targettype" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="finalize">
		<xsd:complexType>
			<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="parallel">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="onentry" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="onexit" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="state" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="datamodel" minOccurs="0" maxOccurs="1" />
				
			</xsd:choice>
			<xsd:attribute name="id" type="xsd:ID" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="history">
		<xsd:complexType>
			<xsd:sequence minOccurs="1" maxOccurs="1">
				<xsd:element ref="transition" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:ID" use="required" />
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="type" type="historytype" />
			<xsd:attribute name="snapshot" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="historytype">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="shallow" />
			<xsd:enumeration value="deep" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:Name" use="required" />
			<xsd:attribute name="expr" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:group name="executablecontent">
		<xsd:choice>
			<xsd:element ref="assign" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="send" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="if" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="log" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="script" minOccurs="0" maxOccurs="unbounded" />
		</xsd:choice>
	</xsd:group>
	
	<xsd:element name="assign">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="location" type="xsd:Name" use="required" />
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="expr" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="send">
		<xsd:complexType>
			<xsd:attribute name="event" type="xsd:string" />
			<xsd:attribute name="target" type="xsd:anyURI" />
			<xsd:attribute name="targettype" type="targettype" default="scxml" />
			<xsd:attribute name="sendid" type="xsd:string" /> <!-- attention: "xsd:string" is not the proper type for the following attribute,
				            rather a string in CSS2 format is required -->
			<xsd:attribute name="delay" type="xsd:string" default="'0s'" />
			<xsd:attribute name="namelist" type="xsd:string" />
			<xsd:attribute name="hints" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="ValueLang.datatype">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:element name="cancel">
		<xsd:complexType>
			<xsd:attribute name="sendid" type="xsd:string" use="required" />
			<xsd:attribute name="sendidexpr" type="ValueLang.datatype"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="if">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="elseif" />
				<xsd:element ref="else" />
				<xsd:group ref="executablecontent" />
			</xsd:choice>
			<xsd:attribute name="cond" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="elseif">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="executablecontent" />
			</xsd:choice>
			<xsd:attribute name="cond" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="else">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="executablecontent" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="log">
		<xsd:complexType>
			<xsd:attribute name="label" type="xsd:string" />
			<xsd:attribute name="expr" type="xsd:string" use="required" />
			
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="script">
		<xsd:complexType mixed="true">
			<xsd:attribute name="src" type="xsd:anyURI"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="targettype">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="scxml" />
			<xsd:enumeration value="webservice" />
		</xsd:restriction>
	</xsd:simpleType> 

</xsd:schema>

=== sousseinglu/PDS-STATE-MACHINE/src/XSD/SCXML_presentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<scxml  version="1.0" initialstate="off" 
		stateMachineName="test"		
	   	userId="testuser"
	   	xmlns="http://www.w3.org/2005/07/scxml" 
	   	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	   	xsi:schemaLocation="http://www.w3.org/2005/07/scxml SCXML_presentation.xsd ">
  <datamodel>
  	<data id="timer" expr="0"></data>
  </datamodel>
  
  <state id="off">
  
  	<transition event="timer.on" target="on">
  		<assign location="timer" expr="timer + 1"></assign>
  	</transition>
  </state>
	
  <state id="on">
  	<transition event="timer.off" target="off"></transition>
  	<transition event="timer.reset" target="off">
  		<assign location="timer" expr="0"></assign>
  	</transition>
  </state>
  <user id="testuser" password="pass"/>
</scxml>
